# IBM Data Analyst Capstone Project
## Module 2 — Data Collection via API

**Goal:** Use the IBM Jobs API to count how many job postings exist for each  
technology (programming languages, databases) and for each city.  
Save results to Excel files for downstream analysis.

In [1]:
# ── CELL 1: Import libraries ───────────────────────────────────────────────────
import requests    # HTTP requests to the API
import pandas as pd  # data manipulation and Excel export
import os           # file-path handling

In [2]:
# ── CELL 2: Define the API base URL ───────────────────────────────────────────
# This IBM-hosted JSON file acts as a mock jobs API
API_URL = (
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/"
    "IBM-DA0321EN-SkillsNetwork/labs/module%201/"
    "Accessing%20Data%20Using%20APIs/jobs.json"
)

In [3]:
# ── CELL 3: Helper — count jobs by technology (Key Skills) ────────────────────
def get_jobs_by_technology(technology):
    """
    Query the API filtering by 'Key Skills'.
    Returns (technology_name, job_count).
    """
    params   = {"Key Skills": technology}   # filter parameter
    response = requests.get(API_URL, params=params)
    count = len(response.json()) if response.ok else 0
    return technology, count

# Quick test
print(get_jobs_by_technology("Python"))

('Python', 27005)

In [4]:
# ── CELL 4: Helper — count jobs by location ───────────────────────────────────
def get_jobs_by_location(location):
    """
    Query the API filtering by 'Location'.
    Returns (location_name, job_count).
    """
    params   = {"Location": location}
    response = requests.get(API_URL, params=params)
    count = len(response.json()) if response.ok else 0
    return location, count

# Quick test
print(get_jobs_by_location("New York"))

('New York', 27005)

In [5]:
# ── CELL 5: Collect job counts for all technologies ───────────────────────────
# List of technologies to query (languages + databases)
technologies = [
    "C", "C#", "C++", "Java", "JavaScript", "Python",
    "Scala", "Oracle", "SQL Server", "MySQL Server",
    "PostgreSQL", "MongoDB"
]

# Fetch counts and store as list of dicts
tech_jobs = []
for tech in technologies:
    name, count = get_jobs_by_technology(tech)
    tech_jobs.append({"Technology": name, "Job_Postings": count})
    print(f"  {name}: {count}")

# Build DataFrame
df_tech = pd.DataFrame(tech_jobs)
df_tech.head()

  C: 27005
  C#: 27005
  C++: 27005
  Java: 27005
  JavaScript: 27005
  Python: 27005
  Scala: 27005
  Oracle: 27005
  SQL Server: 27005
  MySQL Server: 27005
  PostgreSQL: 27005
  MongoDB: 27005

   Technology  Job_Postings
0           C         27005
1          C#         27005
2         C++         27005
3        Java         27005
4  JavaScript         27005

In [6]:
# ── CELL 6: Collect job counts for all target cities ──────────────────────────
locations = [
    "Los Angeles", "New York", "San Francisco",
    "Washington DC", "Seattle", "Austin", "Detroit"
]

loc_jobs = []
for loc in locations:
    name, count = get_jobs_by_location(loc)
    loc_jobs.append({"Location": name, "Job_Postings": count})
    print(f"  {name}: {count}")

df_loc = pd.DataFrame(loc_jobs)
df_loc.head()

  Los Angeles: 27005
  New York: 27005
  San Francisco: 27005
  Washington DC: 27005
  Seattle: 27005
  Austin: 27005
  Detroit: 27005

        Location  Job_Postings
0    Los Angeles         27005
1       New York         27005
2  San Francisco         27005
3  Washington DC         27005
4        Seattle         27005

In [7]:
# ── CELL 7: Save both DataFrames to Excel ─────────────────────────────────────
out_dir = os.path.join("..", "data")
os.makedirs(out_dir, exist_ok=True)   # create data/ folder if it doesn't exist

# Technology job postings
tech_path = os.path.join(out_dir, "job_postings_by_technology.xlsx")
df_tech.to_excel(tech_path, index=False)
print(f"Saved → {tech_path}")

# Location job postings
loc_path = os.path.join(out_dir, "job_postings_by_location.xlsx")
df_loc.to_excel(loc_path, index=False)
print(f"Saved → {loc_path}")

Saved → ..\data\job_postings_by_technology.xlsx
Saved → ..\data\job_postings_by_location.xlsx